name: Github Actions Example
on:
  push:
    branches: 
        - master 
        - 'bugfix/*'
jobs:
  build:
    name: CI test for bugfix
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project
      uses: actions/checkout@v2
    - name: Use Node.js 
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Install dependencies
      run: npm install
    - name: Test project
      run: npm test